### ISSUE TITLE
DLC limit

### ISSUE THREAD

**Issue by jackfavvv** [idlesauce/ps4-eboot-dlc-patcher#12]
92 DLC items were selected and dropped into the terminal:
![unnamed1](https://github.com/idlesauce/ps4-eboot-dlc-patcher/assets/135295326/46b20d29-e2b3-4a11-8ca3-9244ca92a03f)

However, only 76 DLCs were registered to be parsed?
![unnamed](https://github.com/idlesauce/ps4-eboot-dlc-patcher/assets/135295326/2c5143f0-7b7f-4982-a41a-7b957f22b916)

The maximum(99) wasn't exceeded.

**Comment by idlesauce** [comment]
Conemu starts acting wonky for me when pasting a lot of text, by cutting of the end of the text (although im not sure thats whats happening for you too because the chance that it just so happens to cut off in between two arguments is small). Windows terminal also has a fairly small character limit for arguments which is something I hadn't realized. 
For now you can use [this build](https://github.com/idlesauce/ps4-eboot-dlc-patcher/actions/runs/9809559521) which accepts folders as input arguments and finds and parses all pkgs in there (it also parses base and update pkgs to find executables but thats a wip.).  I tried loading over a thousand dlcs and it worked no problem.
Let me know if this works for you!

**Comment by jackfavvv** [comment]
Yeah, I notice that parts of the text does get cut off too on my end. Thanks for the suggestion, I'll give it a try.
