### ISSUE TITLE
[ERROR] This executable doesnt use any functions to get dlc info. This likely means this  game loads dlcs in another executable.

### ISSUE THREAD

**Issue by bi180977** [idlesauce/ps4-eboot-dlc-patcher#13]
![Untitled](https://github.com/user-attachments/assets/b7fe9968-5b3b-4968-a518-68d62f9b0d4c)

As you can probably tell from the pic, it's an issue with Call of Duty World War II. Any ideas on how to fix it boss?
Cheers.

**Comment by idlesauce** [comment]
Some games don't request the dlcs in the `eboot.bin`, its the same deal with other cod games, for example in CoD: Advanced Warfare its `default.elf` and `default_mp.elf` that you need to patch. 

Theres a beta version of the patcher that will automatically find and extract the executables that need patching, to use this set the args to the dlc pkgs, and the update pkg instead of the `eboot.bin`: [https://github.com/idlesauce/ps4-eboot-dlc-patcher/actions/runs/9809559521](https://github.com/idlesauce/ps4-eboot-dlc-patcher/actions/runs/9809559521)

Although since this is a beta version that I didn't test much, it may be wiser to just open the update pkg with it and look for messages like this, that should appear immediately (even before clicking the patch menu option):
```
[INFO] Found executable '/Image0/eboot.bin' in pkg 'C:\game.pkg' which resolves dlc functions
```
And extract and unsign the executables mentioned there manually then patch with the main release version

**Comment by bi180977** [comment]
![Untitled](https://github.com/user-attachments/assets/27ec9528-152d-414c-8e10-1974fdf79917)

Works flawlessly boss. Big thanks for taking the time to help me out.
Cheers.
